name: 'hubspot_source'
version: '0.6.4'

config-version: 2
require-dbt-version: [">=1.0.0", "<2.0.0"]

models:
  hubspot_source:
    +materialized: table
    +schema:
    tmp:
      +materialized: view

vars:
  hubspot_source:
    company: "{{ source('hubspot','company_data') }}"
    company_property_history: "{{ source('hubspot','company_property_history_data') }}"
    contact: "{{ source('hubspot','contact_data') }}"
    contact_merge_audit: "{{ source('hubspot','contact_merge_audit_data') }}"
    contact_list: "{{ source('hubspot','contact_list_data') }}"
    contact_list_member: "{{ source('hubspot','contact_list_member_data') }}"
    contact_property_history: "{{ source('hubspot','contact_property_history_data') }}"
    deal: "{{ source('hubspot','deal_data') }}"
    deal_stage: "{{ source('hubspot','deal_stage_data') }}"
    deal_company: "{{ source('hubspot','deal_company_data') }}"
    deal_contact: "{{ source('hubspot','deal_contact_data') }}"
    deal_pipeline: "{{ source('hubspot','deal_pipeline_data') }}"
    deal_pipeline_stage: "{{ source('hubspot','deal_pipeline_stage_data') }}"
    deal_property_history: "{{ source('hubspot','deal_property_history_data') }}"
    email_campaign: "{{ source('hubspot','email_campaign_data') }}"
    email_event: "{{ source('hubspot','email_event_data') }}"
    email_event_bounce: "{{ source('hubspot','email_event_bounce_data') }}"
    email_event_click: "{{ source('hubspot','email_event_click_data') }}"
    email_event_deferred: "{{ source('hubspot','email_event_deferred_data') }}"
    email_event_delivered: "{{ source('hubspot','email_event_delivered_data') }}"
    email_event_dropped: "{{ source('hubspot','email_event_dropped_data') }}"
    email_event_forward: "{{ source('hubspot','email_event_forward_data') }}"
    email_event_open: "{{ source('hubspot','email_event_open_data') }}"
    email_event_print: "{{ source('hubspot','email_event_print_data') }}"
    email_event_sent: "{{ source('hubspot','email_event_sent_data') }}"
    email_event_spam_report: "{{ source('hubspot','email_event_spam_report_data') }}"
    email_event_status_change: "{{ source('hubspot','email_event_status_change_data') }}"
    engagement: "{{ source('hubspot','engagement_data') }}"
    engagement_call: "{{ source('hubspot','engagement_call_data') }}"
    engagement_company: "{{ source('hubspot','engagement_company_data') }}"
    engagement_contact: "{{ source('hubspot','engagement_contact_data') }}"
    engagement_deal: "{{ source('hubspot','engagement_deal_data') }}"
    engagement_email: "{{ source('hubspot','engagement_email_data') }}"
    engagement_meeting: "{{ source('hubspot','engagement_meeting_data') }}"
    engagement_note: "{{ source('hubspot','engagement_note_data') }}"
    engagement_task: "{{ source('hubspot','engagement_task_data') }}"
    owner: "{{ source('hubspot','owner_data') }}"

    #Service Hub Models
    ticket_company: "{{ source('hubspot','ticket_company_data') }}"
    ticket_contact: "{{ source('hubspot','ticket_contact_data') }}"
    ticket_deal: "{{ source('hubspot','ticket_deal_data') }}"
    ticket_engagement: "{{ source('hubspot','ticket_engagement_data') }}"
    ticket_pipeline: "{{ source('hubspot','ticket_pipeline_data') }}"
    ticket_pipeline_stage: "{{ source('hubspot','ticket_pipeline_stage_data') }}"
    ticket_property_history: "{{ source('hubspot','ticket_property_history_data') }}"
    ticket: "{{ source('hubspot','ticket_data') }}"

    #HubSpot Passthrough Columns
    hubspot__deal_pass_through_columns: []
    hubspot__contact_pass_through_columns: []
    hubspot__company_pass_through_columns: []
    hubspot__ticket_pass_through_columns: []

    #OVERRIDE any ^ passthrough columns by just passing all columns
    hubspot__pass_through_all_columns: false
